---
deployment:
    tasks:
        - export DEPLOYPATH=/home/caiohygi/api/freelancers
        - export FRONTPATH=/home/caiohygi/public_html
        - /bin/cp -r * $DEPLOYPATH
        - /bin/cp -r /front-end/* $FRONTPATH
